before_install: • openssl aes-256-cbc -K $encrypted_79a2f6093848_key -iv Şencrypted_79a2f6893848_iv -in assets/server.key.enc -out assets/server.key -d

sudo: true

before_install:

#

# The before_install steps downloads Salesforce CLI and installs it

#Decrypt server key

#Assign variables
- export CLIURL=https://developer.salesforce.com/media/salesforce-ci/sfdx-linux-amd64.tar.xz

- export SFDX_AUTOUPDATE_DISABLE=false

- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true

- export SFDX_DOMAIN_RETRY=300

- export SFDX_DISABLE_APP_HUB=true

- export SFDX_LOG_LEVEL=DEBUG

- export SFDX_IMPROVED_CODE_COVERAGE=true

#Create SFDX directory

- mkdir sfdx

#install Salesforce CLI

- wget -qo- SCLIURL | tar xl -C sfdx -strip-components 1

- "/sfdx/install"

- export PATH= /sfdx/S(pwd):SPATH

before_script:

# The before script step initializes variables used in the script step and authenticates to the Dev Hub using the JWT-based flow

#Assign variables

- export ROOTDIR-force-app/main/default/

- export TESTLEVEL-RunlocalTests
#Be sure to update the package ID (package ID starts with OHo) or package alias here from the stdx-project.json file

- export PACKAGENAME-"OHo2v000000CawjCAC"

- export PACKAGEVERSION=""

#outputs CLI version

- sfdx --version

#outputs salsforcedx plugin version

- sfdx plugins --core

#Authorizes Dev Hub

- CONSUMERKEY="3MVG9pRzvMkjMb6nHSKz_UfjVwRQhGB55_K2Us7gHwmQtvPTrGQNfKMf5i1J99SO7G.XxQOv2D_3VZuuSUxCi"

- USERNAME="empathetic-bear-tof909.com"

- sfdx force:auth:jwt:grant -clientid $CONSUMERKEY -jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername --setalias HubOrg

script:

#Creates scratch org

- sfdx force:org:create --targetdevhubusername Huborg -setdefaultusername -definitionfile config/project-scratch-def.json --setalias ciorg --wait 10--durationdays 1

- sfdx force:org:display -targetusername ciorg

#Pushes source to scratch org

- sfdx force:source:push -targetusername ciorg

#Runs unit tests on scratch org

- sfdx force:apex:test:run --targetusername ciorg --wait 10 --resultformat tap --codecoverage --testlevelSTESTLEVEL
- stdx force:apex:test:report --targetusername ciorg --verbose --codecoverage
#Deletes scratch org
- sfdx force:org:delete --targetusername ciorg --noprompt

#Creates package version

- PACKAGEVERSION="$(sfdx force:package:version:create --package SPACKAGENAME -installationkeybypass --wait 10 --json --targetdevhubusername HubOrg | jq '.result.SubscriberPackageVersionld" | tr -d "")"

- echo "Package Version Id - "${PACKAGEVERSION}

- echo "Waiting for 5 minutes for package replication"

- sleep 5m

#Creates scratch org

- sfdx force:org:create -targetdevhubusername HubOrg --setdefaultusername --definitionfile config/project-scratch-def.json --setalias installorg --wait 10 --durationdays 1

- sfdx force:org:display --targetusername installorg

#Installs package in scratch org

- sfdx force:package:install --package $PACKAGEVERSION --wait 10 --targetusername installorg
#Runs unit tests on scratch org

- sfdx force:apex:test:run --targetusername installorg --wait 10 --resultformat tap --codecoverage --testlevel$TESTLEVEL
#Deletes scratch org
- sfdx force:org:delete --targetusername installorg --noprompt